export const CodesError = {
  DATA_INVALID: 'DATA_INVALID',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  TICKET_MESSAGE_NOT_FOUND: 'TICKET_MESSAGE_NOT_FOUND',
  FAQ_ENTRY_NOT_FOUND: 'FAQ_ENTRY_NOT_FOUND',
  CHAT_SESSION_NOT_FOUND: 'CHAT_SESSION_NOT_FOUND',
  CHAT_MESSAGE_NOT_FOUND: 'CHAT_MESSAGE_NOT_FOUND',
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  REVIEW_PHOTO_NOT_FOUND: 'REVIEW_PHOTO_NOT_FOUND',
  DUPLICATE_REVIEW: 'DUPLICATE_REVIEW',
} as const;

export type CodesError = (typeof CodesError)[keyof typeof CodesError];
